In [2]:
import os 
os.chdir("/content/drive/My Drive/Advanced Deep Learning/")


In [11]:
import tensorflow as tf
import pickle
import numpy as np

In [25]:
model = tf.keras.models.load_model("model_songsWithTags_20000.h5")
dataset = pickle.load(open('input_spectrograms_2000.pickle', 'rb'))

dataset_X_init = []
dataset_y_init = []
for sample in dataset:
    dataset_X_init.append(sample[0])
    dataset_y_init.append(sample[1])
  
dataset_X = np.array([x[:,:431].reshape((128, 431, 1)) for x in dataset_X_init])
dataset_y = np.array(tf.keras.utils.to_categorical(dataset_y_init, 2))



In [16]:
dataset_X.shape

(1997, 128, 431, 1)

In [17]:
dataset_y.shape

(1997, 2)

In [18]:
score = model.evaluate(x=dataset_X, y=dataset_y)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


63/63 [==============================] - 61s 972ms/step - loss: 0.0955 - accuracy: 0.9825
Test loss: 0.0954938605427742
Test accuracy: 0.9824737310409546


In [23]:
predicted_y = np.argmax(model.predict(dataset_X), axis=-1)

In [24]:
predicted_y

array([1, 1, 0, ..., 1, 1, 1])

In [40]:
missclassified_idx = np.where(predicted_y != np.array(dataset_y_init))[0]

In [32]:
misclassified_genre = np.array(dataset_y_init)[missclassified_idx]

Of this misclassified samples, how many are of each genre 


Hip-hop

In [35]:
sum(misclassified_genre == 0)*100/len(misclassified_genre)

82.85714285714286

Folk 

In [36]:
sum(misclassified_genre == 1)*100/len(misclassified_genre)

17.142857142857142

In [37]:
missclassified_idx

(array([   1,    4,   11,   61,   90,  192,  250,  299,  405,  430,  518,
         635,  709,  722,  953,  990, 1010, 1087, 1109, 1114, 1169, 1217,
        1222, 1251, 1279, 1304, 1370, 1451, 1513, 1530, 1743, 1755, 1794,
        1837, 1944]),)

In [38]:
misclassified_genre

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0.])

In [41]:
missclassified_idx[misclassified_genre==1]

array([1222, 1279, 1304, 1451, 1794, 1837])

In [42]:
missclassified_idx[misclassified_genre==0]

array([   1,    4,   11,   61,   90,  192,  250,  299,  405,  430,  518,
        635,  709,  722,  953,  990, 1010, 1087, 1109, 1114, 1169, 1217,
       1251, 1370, 1513, 1530, 1743, 1755, 1944])